// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "intelligentocx.h"

/////////////////////////////////////////////////////////////////////////////
// CIntelligentOcx

IMPLEMENT_DYNCREATE(CIntelligentOcx, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CIntelligentOcx properties

/////////////////////////////////////////////////////////////////////////////
// CIntelligentOcx operations

long CIntelligentOcx::OcxCreateWindow(LPCTSTR szBusinessData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szBusinessData);
	return result;
}

void CIntelligentOcx::OcxDestroyWindow()
{
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long CIntelligentOcx::OcxDo(LPCTSTR szWorkflowCfg, LPCTSTR szBusinessData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szWorkflowCfg, szBusinessData);
	return result;
}

CString CIntelligentOcx::OcxCall(LPCTSTR szWorkflowCfg, LPCTSTR szBusinessData)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		szWorkflowCfg, szBusinessData);
	return result;
}

long CIntelligentOcx::OcxBegin(LPCTSTR szDllName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szDllName);
	return result;
}

CString CIntelligentOcx::OcxCallFunc(long hDll, LPCTSTR szFuncName, LPCTSTR szParam)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_BSTR;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		hDll, szFuncName, szParam);
	return result;
}

long CIntelligentOcx::OcxEnd(long hDll)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		hDll);
	return result;
}

CString CIntelligentOcx::OcxReadFile(LPCTSTR szFileName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		szFileName);
	return result;
}

void CIntelligentOcx::OcxWriteFile(LPCTSTR szFileName, LPCTSTR szXML)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szFileName, szXML);
}

CString CIntelligentOcx::OcxGetOcxPath(LPCTSTR szGuid)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		szGuid);
	return result;
}

void CIntelligentOcx::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
