#if !defined(AFX_INTELLIGENTOCX_H__5CF74522_DE23_421A_9E0B_D543C88CFACB__INCLUDED_)
#define AFX_INTELLIGENTOCX_H__5CF74522_DE23_421A_9E0B_D543C88CFACB__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CIntelligentOcx wrapper class

class CIntelligentOcx : public CWnd
{
protected:
	DECLARE_DYNCREATE(CIntelligentOcx)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x97162609, 0xfb4, 0x4c5f, { 0x86, 0x78, 0x79, 0xec, 0x3d, 0x23, 0x40, 0x61 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long OcxCreateWindow(LPCTSTR szBusinessData);
	void OcxDestroyWindow();
	long OcxDo(LPCTSTR szWorkflowCfg, LPCTSTR szBusinessData);
	CString OcxCall(LPCTSTR szWorkflowCfg, LPCTSTR szBusinessData);
	long OcxBegin(LPCTSTR szDllName);
	CString OcxCallFunc(long hDll, LPCTSTR szFuncName, LPCTSTR szParam);
	long OcxEnd(long hDll);
	CString OcxReadFile(LPCTSTR szFileName);
	void OcxWriteFile(LPCTSTR szFileName, LPCTSTR szXML);
	CString OcxGetOcxPath(LPCTSTR szGuid);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_INTELLIGENTOCX_H__5CF74522_DE23_421A_9E0B_D543C88CFACB__INCLUDED_)
