/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_webutil_WriteConsole */

#ifndef _Included_cn_com_webutil_WriteConsole
#define _Included_cn_com_webutil_WriteConsole
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     cn_com_webutil_WriteConsole
	* Method:    getDate
	* Signature: ()Ljava/lang/String;
	*/
	JNIEXPORT jstring JNICALL Java_cn_com_webutil_WriteConsole_getDate
		(JNIEnv *, jobject);

	/*
	* Class:     cn_com_webutil_WriteConsole
	* Method:    sayHello
	* Signature: (Ljava/lang/String;)V
	*/
	JNIEXPORT void JNICALL Java_cn_com_webutil_WriteConsole_sayHello
		(JNIEnv *, jobject, jstring);

	/*
	* Class:     cn_com_webutil_WriteConsole
	* Method:    sayGoodye
	* Signature: (Lcn/com/webutil/WriteConsole;)Ljava/lang/String;
	*/
	JNIEXPORT jstring JNICALL Java_cn_com_webutil_WriteConsole_sayGoodye
		(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
