// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "ocxdemo.h"

/////////////////////////////////////////////////////////////////////////////
// COcxDemo

IMPLEMENT_DYNCREATE(COcxDemo, CWnd)

/////////////////////////////////////////////////////////////////////////////
// COcxDemo properties

/////////////////////////////////////////////////////////////////////////////
// COcxDemo operations

void COcxDemo::CreateBtnAdd()
{
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
