#if !defined(AFX_OCXDEMO_H__712CB749_2C99_47C5_B24D_8D618AC3CEAA__INCLUDED_)
#define AFX_OCXDEMO_H__712CB749_2C99_47C5_B24D_8D618AC3CEAA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// COcxDemo wrapper class

class COcxDemo : public CWnd
{
protected:
	DECLARE_DYNCREATE(COcxDemo)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x5adf8b8c, 0x6e5b, 0x4ec9, { 0xa6, 0x45, 0xb7, 0xa3, 0x48, 0xf6, 0xf2, 0x6f } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void CreateBtnAdd();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_OCXDEMO_H__712CB749_2C99_47C5_B24D_8D618AC3CEAA__INCLUDED_)
