#pragma once
#define FQDK_KEY				        _T("FQ_Key")
#define FQDK_MODULECLSID			    _T("FQ_ModuleClsID")
#define FQDK_SENDER				        _T("FQ_Sender")
#define FQDK_TIPTITLE				    _T("FQ_TipTitle")
#define FQDK_TIPCONTENT				    _T("FQ_TipContent")
#define FQDK_TIPYESBTNNAME  			_T("FQ_TipYesButtonName")
#define FQDK_TIPNOBTNNAME  				_T("FQ_TipNoButtonName")

#define FQDK_USER_MEMONAME				_T("FQ_UserMemoName")
#define FQDK_USER_HOSTNAME				_T("FQ_UserHostName")
#define FQDK_USER_LOGINNAME				_T("FQ_UserLoginName")
#define FQDK_USER_PERSONSIGN			_T("FQ_UserPersonSign")
#define FQDK_USER_MEMOGROUP				_T("FQ_UserMemoGroup")
#define FQDK_USER_GROUP					_T("FQ_UserGroup")
#define FQDK_USER_IP					_T("FQ_UserIP")
#define FQDK_USER_MAC					_T("FQ_UserMAC")
#define FQDK_USER_NAME					_T("FQ_UserName")
#define FQDK_USER_VERSION				_T("FQ_Version")

#define FQDK_SEL_ISGROUP		    	_T("FQ_SelIsGroup")
#define FQDK_SEL_AUTOGROUP				_T("FQ_SelAutoGroup")
#define FQDK_SEL_GROUPNAME				_T("FQ_SelGroupName")
	
#define FQDK_FACE_SELPATHNAME			_T("FQ_FaceSelPathName")
#define FQDK_DAY_SELDATE				_T("FQ_DaySelDate")
#define FQDK_CLOCK_DAYKEY				_T("FQ_ClockDayKey")